# Generated by Django 4.1.6 on 2023-02-16 02:50

import blur_image.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=15, verbose_name='Name Image')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blur_image.utils.image_upload_location, verbose_name='Image')),
                ('is_blur', models.BooleanField(default=False, verbose_name='Is Blur?')),
            ],
        ),
    ]
