# Generated by Django 4.1.6 on 2023-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blur_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
